
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.cLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class frmPrincipal extends javax.swing.JFrame {

    // Método para cambiar el contenido principal del JFrame
    public void mostrarPanel(javax.swing.JPanel panelNuevo) {
        getContentPane().removeAll();      // Elimina todo lo que hay en el JFrame
        getContentPane().add(panelNuevo);  // Añade el nuevo panel que quieres mostrar
        getContentPane().revalidate();     // Refresca el layout para que se actualice
        getContentPane().repaint();        // Repinta la ventana para que se vea bien
    }

    public frmPrincipal() {
        initComponents();

        // Control inicial al abrir el formulario
        if (cbrol.getSelectedItem().toString().equalsIgnoreCase("ROL USUARIO")) {
            txtcontrasena.setEnabled(false);
            txtcontrasena.setText("");
        } else {
            txtcontrasena.setEnabled(true);
        }

        // Evento al cambiar el rol
        cbrol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    String rolSeleccionado = cbrol.getSelectedItem().toString();
                    if (rolSeleccionado.equalsIgnoreCase("ROL USUARIO")) {
                        txtcontrasena.setEnabled(false);
                        txtcontrasena.setText("");
                    } else {
                        txtcontrasena.setEnabled(true); // si el rol no es usuario activo la caja de la contrasena
                        txtcontrasena.requestFocus();
                    }
                }
            }
        });
        txtcontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btniniciarsesion.doClick();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelpie = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbfondo = new javax.swing.JLabel();
        lbcontrasena = new javax.swing.JLabel();
        cbrol = new javax.swing.JComboBox<>();
        lbusuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btniniciarsesion = new javax.swing.JButton();
        txtcontrasena = new javax.swing.JPasswordField();

        Panelpie.setBackground(new java.awt.Color(255, 0, 255));
        Panelpie.setPreferredSize(new java.awt.Dimension(1046, 25));

        javax.swing.GroupLayout PanelpieLayout = new javax.swing.GroupLayout(Panelpie);
        Panelpie.setLayout(PanelpieLayout);
        PanelpieLayout.setHorizontalGroup(
            PanelpieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        PanelpieLayout.setVerticalGroup(
            PanelpieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        lbfondo.setBackground(new java.awt.Color(0, 0, 0));
        lbfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logologin-modified.png"))); // NOI18N
        lbfondo.setOpaque(true);
        lbfondo.setPreferredSize(new java.awt.Dimension(1080, 1076));
        jPanel3.add(lbfondo);
        lbfondo.setBounds(50, 10, 560, 490);

        lbcontrasena.setBackground(new java.awt.Color(0, 0, 0));
        lbcontrasena.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        lbcontrasena.setText("CONTRASENA");
        lbcontrasena.setOpaque(true);
        jPanel3.add(lbcontrasena);
        lbcontrasena.setBounds(740, 310, 140, 50);

        cbrol.setBackground(new java.awt.Color(204, 102, 255));
        cbrol.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROL USUARIO", "GERENTE", "VENDEDOR", " " }));
        cbrol.setOpaque(true);
        cbrol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbrolItemStateChanged(evt);
            }
        });
        jPanel3.add(cbrol);
        cbrol.setBounds(720, 270, 150, 40);

        lbusuario.setBackground(new java.awt.Color(0, 0, 0));
        lbusuario.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbusuario.setForeground(new java.awt.Color(255, 255, 255));
        lbusuario.setText("  USUARIO");
        lbusuario.setOpaque(true);
        jPanel3.add(lbusuario);
        lbusuario.setBounds(730, 220, 140, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/login.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(700, 20, 210, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon user.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(690, 270, 74, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/candado.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(690, 360, 30, 40);

        btniniciarsesion.setBackground(new java.awt.Color(0, 0, 0));
        btniniciarsesion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btniniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        btniniciarsesion.setText("INICIAR SESION");
        btniniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarsesionActionPerformed(evt);
            }
        });
        jPanel3.add(btniniciarsesion);
        btniniciarsesion.setBounds(720, 410, 150, 50);

        txtcontrasena.setBackground(new java.awt.Color(204, 102, 255));
        txtcontrasena.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel3.add(txtcontrasena);
        txtcontrasena.setBounds(720, 360, 150, 40);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarsesionActionPerformed
        String rolSeleccionado = cbrol.getSelectedItem().toString();
        String claveIngresada = txtcontrasena.getText();
        cLogin controladorLogin = new cLogin();

        if (controladorLogin.validar(claveIngresada, rolSeleccionado)) {
            JOptionPane.showMessageDialog(this, "Bienvenido " + rolSeleccionado);

            if (rolSeleccionado.equalsIgnoreCase("GERENTE")) {
                panelGerente pg = new panelGerente();
                pg.setPrincipal(this);           // ← le pasamos la referencia al JFrame actual
                mostrarPanel(pg);
            } else if (rolSeleccionado.equalsIgnoreCase("VENDEDOR")) {
                mostrarPanel(new panelVendedor()); // O cualquier otro panel para vendedor
            }
        } else {
            JOptionPane.showMessageDialog(this, "Clave o rol incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            txtcontrasena.setText("");
        }
    }//GEN-LAST:event_btniniciarsesionActionPerformed

    private void cbrolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbrolItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String rolSeleccionado = cbrol.getSelectedItem().toString();
            if (rolSeleccionado.equalsIgnoreCase("ROL USUARIO")) {
                txtcontrasena.setEnabled(false);
                txtcontrasena.setText("");
            } else {
                txtcontrasena.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cbrolItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelpie;
    private javax.swing.JButton btniniciarsesion;
    private javax.swing.JComboBox<String> cbrol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbcontrasena;
    private javax.swing.JLabel lbfondo;
    private javax.swing.JLabel lbusuario;
    private javax.swing.JPasswordField txtcontrasena;
    // End of variables declaration//GEN-END:variables

    private static class panelcentral {

        private static void add(panelGerente pg, String panelGerente) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public panelcentral() {
        }
    }
}
