/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelos.Cliente;
import Controladores.cCliente;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PanelClientes extends javax.swing.JPanel {

    private cCliente cCliente;

    public PanelClientes() {
        initComponents();
        limpiar();
        cCliente = new cCliente();
        try {
            cCliente.leer(); // carga desde CSV
            actualizarTabla();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer datos: " + ex.getMessage());
        }
    }

    private void actualizarTabla() {
        Tabla.setModel(cCliente.getTabla());
    }

    public void actualizarTabla(ArrayList<Cliente> lista) {
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        modelo.setRowCount(0);
        for (Cliente c : lista) {
            Object[] fila = {c.cedula, c.nombre,c.apellido,c.celular,c.direccion,c.ciudad,c.email};
            modelo.addRow(fila);
        }
    }

    private void limpiar() {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCelular.setText("");
        txtDireccion.setText("");
        txtCiudad.setText("");
        txtbuscarnombre.setText("");
        txtEmail.setText("");
        txtCedula.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnmodificar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        btnliminar = new javax.swing.JButton();
        txtbuscarnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 255, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(102, 255, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 190, 40));

        Tabla.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula:", "Nombre:", "Apellido:", "Celular:", "Direcccion:", "Ciudad:", "Email:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 720, 210));

        btnmodificar.setBackground(new java.awt.Color(0, 0, 0));
        btnmodificar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(102, 255, 0));
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 190, 39));

        btnagregar.setBackground(new java.awt.Color(0, 0, 0));
        btnagregar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(102, 255, 0));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon user.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 37));

        btnliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnliminar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnliminar.setForeground(new java.awt.Color(51, 255, 0));
        btnliminar.setText("Eliminar");
        btnliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnliminarActionPerformed(evt);
            }
        });
        add(btnliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 190, 37));

        txtbuscarnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarnombreActionPerformed(evt);
            }
        });
        txtbuscarnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarnombreKeyReleased(evt);
            }
        });
        add(txtbuscarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 170, 40));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 0));
        jLabel2.setText("Cedula");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 93, 20));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 0));
        jLabel6.setText("Nombre");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 0));
        jLabel7.setText("Ciudad");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 20));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 0));
        jLabel8.setText("Celular");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 20));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 0));
        jLabel9.setText("Apellido");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 0));
        jLabel10.setText("Direccion");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        Email.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(102, 255, 0));
        Email.setText("Email");
        add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 20));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, -1));

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, -1));

        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });
        add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 200, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 255, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/lupa (2).png"))); // NOI18N
        btnBuscar.setText("Criterio de Busqueda");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 220, 42));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/Imagen de WhatsApp 2025-07-18 a las 16.17.42_7cd80df7.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 960, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

        String cedula = txtCedula.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String celular = txtCelular.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String ciudad = txtCiudad.getText().trim();
        String email = txtbuscarnombre.getText().trim();

// Validación de campos vacíos
        if (cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || celular.isEmpty() || direccion.isEmpty() || ciudad.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos antes de agregar.");
            return;
        }

// Crear el cliente
        Cliente nuevoCliente = new Cliente(cedula, nombre, apellido, celular, direccion, ciudad, email);

        try {
            cCliente.nuevo(nuevoCliente);  // agrega a la lista
            cCliente.guardar();            // guarda en CSV
            actualizarTabla();             // actualiza la tabla
            JOptionPane.showMessageDialog(this, "Cliente agregado con éxito.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar cliente: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnliminarActionPerformed
        int filaSeleccionada = Tabla.getSelectedRow(); // Verifica si hay una fila seleccionada
        if (filaSeleccionada != -1) {
            String cedula = Tabla.getValueAt(filaSeleccionada, 0).toString(); // Supone que la cédula está en la columna 0

            // Mostrar diálogo de confirmación
            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de que deseas eliminar al cliente con cédula " + cedula + "?",
                    "Confirmación de eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION) {
                try {

                    cCliente.eliminar(cedula); // Elimina del controlador
                    cCliente.guardar(); // Guarda cambios
                    Tabla.setModel(cCliente.getTabla()); // Refresca tabla

                    JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito.");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
                } catch (RuntimeException rex) {
                    JOptionPane.showMessageDialog(this, rex.getMessage());
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente para eliminar.");
        }

    }//GEN-LAST:event_btnliminarActionPerformed

    private void txtbuscarnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarnombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombreBuscar = txtbuscarnombre.getText().trim();

        if (nombreBuscar.isEmpty()) {
            // Si el campo está vacío, muestra toda la lista
            Tabla.setModel(cCliente.getTabla());
            return;
        }

        try {
            cCliente resultado = cCliente.buscar_nombre(nombreBuscar);
            Tabla.setModel(resultado.getTabla()); // muestra solo los resultados filtrados
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en la búsqueda: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       int filaSeleccionada = Tabla.getSelectedRow();
if (filaSeleccionada == -1) {
    JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla para modificar.");
    return;
}

// Obtener datos del formulario
String cedula = txtCedula.getText().trim();
String nombre = txtNombre.getText().trim();
String apellido = txtApellido.getText().trim();
String celular = txtCelular.getText().trim();
String direccion = txtDireccion.getText().trim();
String ciudad = txtCiudad.getText().trim();
String email = txtEmail.getText().trim();

// Validación de campos
if (cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty()
        || celular.isEmpty() || direccion.isEmpty() || ciudad.isEmpty() || email.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
    return;
}

// Obtener datos actuales desde la tabla
String cedulaOriginal = Tabla.getValueAt(filaSeleccionada, 0).toString();
String nombreOriginal = Tabla.getValueAt(filaSeleccionada, 1).toString();
String apellidoOriginal = Tabla.getValueAt(filaSeleccionada, 2).toString();
String celularOriginal = Tabla.getValueAt(filaSeleccionada, 3).toString();
String direccionOriginal = Tabla.getValueAt(filaSeleccionada, 4).toString();
String ciudadOriginal = Tabla.getValueAt(filaSeleccionada, 5).toString();
String emailOriginal = Tabla.getValueAt(filaSeleccionada, 6).toString();

// Verificar si hay cambios
if (cedula.equals(cedulaOriginal) && nombre.equals(nombreOriginal) && apellido.equals(apellidoOriginal)
        && celular.equals(celularOriginal) && direccion.equals(direccionOriginal)
        && ciudad.equals(ciudadOriginal) && email.equals(emailOriginal)) {
    JOptionPane.showMessageDialog(this, "No ha realizado ningún cambio.");
    return;
}

try {
    // Crear objeto actualizado
    Cliente nuevo = new Cliente(cedula, nombre, apellido, celular, direccion, ciudad, email);

    // Lógica de modificación
    cCliente.modificar(nuevo, cedulaOriginal);
    cCliente.guardar(); // guarda cambios en CSV
    actualizarTabla();  // refresca tabla
    JOptionPane.showMessageDialog(this, "Cliente modificado con éxito.");
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error al modificar cliente: " + ex.getMessage());
}
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        int fila = Tabla.getSelectedRow();
        if (fila >= 0) {
            txtCedula.setText(Tabla.getValueAt(fila, 0).toString());
            txtNombre.setText(Tabla.getValueAt(fila, 1).toString());
            txtApellido.setText(Tabla.getValueAt(fila, 2).toString());
            txtCelular.setText(Tabla.getValueAt(fila, 3).toString());
            txtDireccion.setText(Tabla.getValueAt(fila, 4).toString());
            txtCiudad.setText(Tabla.getValueAt(fila, 5).toString());
            txtEmail.setText(Tabla.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtbuscarnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarnombreKeyReleased
        try {
            String texto = txtbuscarnombre.getText().trim();
            ArrayList<Cliente> resultados = cCliente.buscarClientes(texto);
            actualizarTabla(resultados);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar clientes: " + e.getMessage());
        }
    }//GEN-LAST:event_txtbuscarnombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtbuscarnombre;
    // End of variables declaration//GEN-END:variables
}
