/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class panelGerente extends javax.swing.JPanel {

    private frmPrincipal principal;
    private PanelClientes PanelClientes;
    private panelVendedor panelVendedor;
    private Panelproductos Panelproductos;
    private panelFactura PanelFactura;

    /**
     * Creates new form panelGerente
     */
    public panelGerente() {
        initComponents();
        PanelClientes = new PanelClientes();                      // ← AÑADE ESTO
        panelcentral.add(PanelClientes, "clientes");
        panelVendedor = new panelVendedor();                      // ← NUEVO
        panelcentral.add(panelVendedor, "vendedor");
        Panelproductos = new Panelproductos();                    // ← NUEVO
        panelcentral.add(Panelproductos, "productos");
        PanelFactura = new panelFactura();
        panelcentral.add(PanelFactura, "Facturacion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnusuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnfactura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btncliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnvendedor = new javax.swing.JButton();
        btnproductos = new javax.swing.JButton();
        btnsalir1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelcentral = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(255, 255, 0));
        setLayout(new java.awt.BorderLayout());

        panelmenu.setBackground(new java.awt.Color(0, 0, 0));
        panelmenu.setPreferredSize(new java.awt.Dimension(200, 200));
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/factura-removebg-preview (1).png"))); // NOI18N
        panelmenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/user_3237472 (1).png"))); // NOI18N
        panelmenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        btnusuario.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/steak_1852275.png"))); // NOI18N
        btnusuario.setText("USUARIO");
        btnusuario.setBorder(null);
        btnusuario.setContentAreaFilled(false);
        btnusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusuarioMouseClicked(evt);
            }
        });
        btnusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuarioActionPerformed(evt);
            }
        });
        panelmenu.add(btnusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/man-and-woman-user-26904-removebg-preview.png"))); // NOI18N
        panelmenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/user_3237472 (1).png"))); // NOI18N
        panelmenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btnfactura.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnfactura.setForeground(new java.awt.Color(255, 255, 255));
        btnfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/steak_1852275.png"))); // NOI18N
        btnfactura.setText("FACTURACION");
        btnfactura.setBorder(null);
        btnfactura.setContentAreaFilled(false);
        btnfactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaActionPerformed(evt);
            }
        });
        panelmenu.add(btnfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/vendedor-removebg-preview.png"))); // NOI18N
        panelmenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 90, 90));

        btncliente.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btncliente.setForeground(new java.awt.Color(255, 255, 255));
        btncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/steak_1852275.png"))); // NOI18N
        btncliente.setText("CLIENTES");
        btncliente.setBorder(null);
        btncliente.setContentAreaFilled(false);
        btncliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });
        panelmenu.add(btncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/productos.png"))); // NOI18N
        panelmenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 110, 120));

        btnvendedor.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnvendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnvendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/steak_1852275.png"))); // NOI18N
        btnvendedor.setText("VENDEDOR");
        btnvendedor.setBorder(null);
        btnvendedor.setContentAreaFilled(false);
        btnvendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendedorActionPerformed(evt);
            }
        });
        panelmenu.add(btnvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, -1));

        btnproductos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnproductos.setForeground(new java.awt.Color(255, 255, 255));
        btnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/steak_1852275.png"))); // NOI18N
        btnproductos.setText("PRODUCTOS");
        btnproductos.setBorder(null);
        btnproductos.setContentAreaFilled(false);
        btnproductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        panelmenu.add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnsalir1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnsalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/steak_1852275.png"))); // NOI18N
        btnsalir1.setText("Salir ");
        btnsalir1.setBorder(null);
        btnsalir1.setContentAreaFilled(false);
        btnsalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir1ActionPerformed(evt);
            }
        });
        panelmenu.add(btnsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        add(panelmenu, java.awt.BorderLayout.LINE_START);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("jLabel10");
        jLabel10.setOpaque(true);
        add(jLabel10, java.awt.BorderLayout.PAGE_END);

        panelcentral.setLayout(new java.awt.CardLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Recursos/Imagen de WhatsApp 2025-07-18 a las 16.17.42_7cd80df7.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setOpaque(true);
        panelcentral.add(jLabel11, "card2");

        add(panelcentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendedorActionPerformed
        CardLayout cl = (CardLayout) panelcentral.getLayout();
        cl.show(panelcentral, "vendedor");
    }//GEN-LAST:event_btnvendedorActionPerformed

    private void btnusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuarioActionPerformed

    }//GEN-LAST:event_btnusuarioActionPerformed

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        CardLayout cl = (CardLayout) panelcentral.getLayout();
        cl.show(panelcentral, "clientes");
    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuarioMouseClicked

    }//GEN-LAST:event_btnusuarioMouseClicked

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        CardLayout cl = (CardLayout) panelcentral.getLayout();
        cl.show(panelcentral, "productos");
    }//GEN-LAST:event_btnproductosActionPerformed

    private void btnfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaActionPerformed
        CardLayout cl = (CardLayout) panelcentral.getLayout();
        cl.show(panelcentral, "Facturacion");
    }//GEN-LAST:event_btnfacturaActionPerformed

    private void btnsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir1ActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas cerrar sesión?",
                "Confirmar cierre de sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Cerramos el frmPrincipal
            if (principal != null) {
                principal.dispose(); // cierra completamente el JFrame
            }

            // Abrimos una nueva instancia del frmPrincipal (que funciona como frmLogin)
            frmPrincipal login = new frmPrincipal();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnsalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnfactura;
    private javax.swing.JButton btnproductos;
    private javax.swing.JButton btnsalir1;
    private javax.swing.JButton btnusuario;
    private javax.swing.JButton btnvendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelcentral;
    private javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables

    public void setPrincipal(frmPrincipal principal) {
        this.principal = principal;
    }
}
